timeline
    title Короткая история Панамского канала
    1880-е : французская попытка строительства
    1904 : старт американского этапа строительства
    1914 : канал открыт для судоходства
    1999 : управление окончательно переходит Панаме
    2016 : открывается расширенный канал с новыми шлюзами
